# Generated by Django 3.0.4 on 2020-03-25 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('idArticle', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dateAr', models.DateTimeField(auto_now=True)),
                ('contenuAr', models.TextField()),
                ('validerAR', models.BooleanField(default=False)),
                ('idModerateurAr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idRedacteurAr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_redacteur', to=settings.AUTH_USER_MODEL, verbose_name='redacteur')),
            ],
        ),
        migrations.CreateModel(
            name='videoArticle',
            fields=[
                ('idVideo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lienViAc', models.CharField(max_length=255)),
                ('idArticleVd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Articles.article', verbose_name='article')),
            ],
        ),
        migrations.CreateModel(
            name='photoArticle',
            fields=[
                ('idPhoto', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lienPhAc', models.CharField(max_length=255)),
                ('idArticlePh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Articles.article', verbose_name='article')),
            ],
        ),
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('idCommentaire', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('contenuCom', models.TextField()),
                ('signalerCom', models.BooleanField(default=False)),
                ('idArticleCom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Articles.article', verbose_name='article')),
                ('idModerateurCom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='com_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idUtilisateurCom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='com_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
    ]
