# Generated by Django 3.0.3 on 2020-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='terminerAR',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dateAr',
            field=models.DateTimeField(verbose_name='date de redaction'),
        ),
    ]
