# Generated by Django 3.0.4 on 2020-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarticle',
            name='lienPhAc',
            field=models.ImageField(upload_to='article_images/', verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='lienViAc',
            field=models.FileField(upload_to='article_videos/', verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='videothematique',
            name='lienVthema',
            field=models.FileField(upload_to='video_thematique/', verbose_name='lien'),
        ),
    ]
