# Generated by Django 3.0.4 on 2020-03-25 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='idModerateurAr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='idRedacteurAr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_redacteur', to=settings.AUTH_USER_MODEL, verbose_name='redacteur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='idArticleCom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='idModerateurCom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='idUtilisateurCom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='photoarticle',
            name='idArticlePh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='idArticleVd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article', verbose_name='article'),
        ),
    ]
