# Generated by Django 3.0.4 on 2020-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20200325_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenuAr',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dateAr',
            field=models.DateTimeField(auto_now=True, verbose_name='date de redaction'),
        ),
        migrations.AlterField(
            model_name='article',
            name='validerAR',
            field=models.BooleanField(default=False, verbose_name='Validée'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenuCom',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='signalerCom',
            field=models.BooleanField(default=False, verbose_name='signalé'),
        ),
        migrations.AlterField(
            model_name='photoarticle',
            name='lienPhAc',
            field=models.CharField(max_length=255, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='lienViAc',
            field=models.CharField(max_length=255, verbose_name='lien'),
        ),
    ]
