# Generated by Django 3.0.3 on 2020-04-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20200423_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='refuserAR',
        ),
    ]
