# Generated by Django 2.2.13 on 2020-07-02 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_remove_article_refuserar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videothematique',
            name='refuserVthema',
        ),
        migrations.AlterField(
            model_name='videothematique',
            name='idModerateurVthema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='videothematique',
            name='validerVthema',
            field=models.BooleanField(default=None, verbose_name='validée'),
        ),
    ]
