# Generated by Django 3.0.4 on 2020-03-25 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='videoThematique',
            fields=[
                ('idVideoThema', models.AutoField(primary_key=True, serialize=False)),
                ('lienVthema', models.CharField(max_length=255)),
                ('validerVthema', models.BooleanField(default=False)),
                ('titreVthema', models.CharField(max_length=255)),
                ('descriptionVthema', models.TextField()),
                ('idModerateurVthema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vid_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idUtilisateurVThema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vid_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='signalement',
            fields=[
                ('idSignal', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descriptionSg', models.TextField()),
                ('validerSg', models.BooleanField(default=False)),
                ('dateSg', models.DateTimeField(auto_now=True)),
                ('typeSg', models.CharField(choices=[('ph', 'photo'), ('vi', 'video')], max_length=2)),
                ('lienSg', models.CharField(max_length=255)),
                ('idModerateurSg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sign_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idUtilisateurSg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sign_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='selfPhoto',
            fields=[
                ('idSelfPhoto', models.AutoField(primary_key=True, serialize=False)),
                ('lienSph', models.CharField(max_length=255)),
                ('validerSph', models.BooleanField(default=False)),
                ('idModerateurSph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sphoto_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idUtilisateurSph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sphoto_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
    ]
