# Generated by Django 3.0.4 on 2020-03-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='signalement',
            fields=[
                ('idSignal', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descriptionSg', models.TextField(verbose_name='Description')),
                ('validerSg', models.BooleanField(blank=True, default=False, null=True, verbose_name='validée')),
                ('refuserSg', models.BooleanField(blank=True, default=False, null=True, verbose_name='refusée')),
                ('dateSg', models.DateTimeField(auto_now=True, verbose_name='Date de signalement')),
                ('typeSg', models.CharField(choices=[('ph', 'photo'), ('vi', 'video')], max_length=2, verbose_name='type')),
                ('lienSg', models.CharField(max_length=255, verbose_name='lien')),
                ('idModerateurSg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idUtilisateurSg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='selfPhoto',
            fields=[
                ('idSelfPhoto', models.AutoField(primary_key=True, serialize=False)),
                ('lienSph', models.CharField(max_length=255, verbose_name='lien')),
                ('idModerateurSph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sphoto_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idUtilisateurSph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sphoto_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
    ]
