# Generated by Django 3.0.4 on 2020-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='lienSg',
            field=models.ImageField(upload_to='signalement/', verbose_name='lien'),
        ),
    ]
