# Generated by Django 3.0.4 on 2020-03-25 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Signal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfphoto',
            name='idModerateurSph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sphoto_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='selfphoto',
            name='idUtilisateurSph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sphoto_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='idModerateurSg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='idUtilisateurSg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='videothematique',
            name='idModerateurVthema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AlterField(
            model_name='videothematique',
            name='idUtilisateurVThema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
