# Generated by Django 3.0.3 on 2020-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signal', '0002_auto_20200423_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='refuserSg',
        ),
        migrations.AlterField(
            model_name='signalement',
            name='validerSg',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='validé'),
        ),
    ]
