# Generated by Django 3.0.3 on 2020-06-04 16:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Signal', '0003_auto_20200528_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailCCC',
            fields=[
                ('idEmail', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField(verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('email_from', models.EmailField(max_length=254, verbose_name='source')),
                ('recipient_list', django_mysql.models.ListTextField(models.EmailField(max_length=254), size=100)),
            ],
        ),
    ]
