# Generated by Django 2.2.13 on 2020-06-24 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Signal', '0004_emailccc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='idUtilisateurSg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
