# Generated by Django 2.2.13 on 2020-06-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signal', '0005_auto_20200624_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='lienSg',
            field=models.FileField(upload_to='signalement/', verbose_name='lien'),
        ),
    ]
