# Generated by Django 2.2.13 on 2020-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signal', '0006_auto_20200624_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailccc',
            name='attach',
            field=models.TextField(default=None, verbose_name='piece jointe'),
            preserve_default=False,
        ),
    ]
