# Generated by Django 3.0.4 on 2020-03-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosante',
            options={'verbose_name_plural': 'Infos Sante'},
        ),
    ]
