# Generated by Django 3.0.3 on 2020-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosante',
            name='dateSaisie',
            field=models.DateTimeField(verbose_name='date de saisie'),
        ),
    ]
