# Generated by Django 3.0.4 on 2020-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sante', '0003_auto_20200325_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosante',
            name='Rythme_cardiaque',
            field=models.FloatField(default=0, verbose_name='rythme cardiaque'),
        ),
        migrations.AlterField(
            model_name='infosante',
            name='dateSaisie',
            field=models.DateTimeField(auto_now=True, verbose_name='date de saisie'),
        ),
    ]
