# Generated by Django 3.0.3 on 2020-03-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compteutilisateur',
            old_name='nomUtilisateur',
            new_name='username',
        ),
    ]
