# Generated by Django 3.0.4 on 2020-04-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0003_compteutilisateur_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteutilisateur',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='compteutilisateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='nom'),
        ),
    ]
