# Generated by Django 3.0.4 on 2020-04-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0004_auto_20200408_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteutilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='compteutilisateur',
            name='last_name',
        ),
    ]
