# Generated by Django 3.0.3 on 2020-04-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0005_auto_20200409_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compteutilisateur',
            old_name='idUtilisateur',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='infopersonel',
            name='dateNaissance',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='infopersonel',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infopersonel',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infopersonel',
            name='wilaya',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
