# Generated by Django 3.0.3 on 2020-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0007_auto_20200418_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Type',
            field=models.CharField(choices=[('si', 'simple'), ('rd', 'redacteur'), ('md', 'moderateur'), ('as', 'agentsante'), ('ad', 'admin')], max_length=2),
        ),
    ]
