# Generated by Django 3.0.4 on 2020-03-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pubFacebook',
            fields=[
                ('idPubFacebook', models.AutoField(primary_key=True, serialize=False)),
                ('lienPubFb', models.CharField(max_length=255)),
                ('DateFb', models.DateTimeField()),
                ('validerFb', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pubSiteWeb',
            fields=[
                ('idPubWeb', models.AutoField(primary_key=True, serialize=False)),
                ('lienPubWeb', models.CharField(max_length=255)),
                ('DateSw', models.DateTimeField()),
                ('validerSw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pubYoutube',
            fields=[
                ('idPubYoutube', models.AutoField(primary_key=True, serialize=False)),
                ('lienPubYt', models.CharField(max_length=255)),
                ('DateYt', models.DateTimeField()),
                ('validerYt', models.BooleanField(default=False)),
            ],
        ),
    ]
