# Generated by Django 3.0.3 on 2020-03-28 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pubYoutube',
            fields=[
                ('idPubYoutube', models.AutoField(primary_key=True, serialize=False)),
                ('lienPubYt', models.CharField(max_length=255, verbose_name='lien')),
                ('DateYt', models.DateTimeField(verbose_name='date de publication')),
                ('validerYt', models.BooleanField(blank=True, default=False, null=True, verbose_name='validée')),
                ('refuserYt', models.BooleanField(blank=True, default=False, null=True, verbose_name='refusée')),
                ('idModerateurYt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yt_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
            ],
        ),
        migrations.CreateModel(
            name='pubSiteWeb',
            fields=[
                ('idPubWeb', models.AutoField(primary_key=True, serialize=False)),
                ('lienPubWeb', models.CharField(max_length=255, verbose_name='lien')),
                ('DateSw', models.DateTimeField(verbose_name='date de publication')),
                ('validerSw', models.BooleanField(blank=True, default=False, null=True, verbose_name='validée')),
                ('refuserSw', models.BooleanField(blank=True, default=False, null=True, verbose_name='refusée')),
                ('idModerateurSw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sw_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
            ],
        ),
        migrations.CreateModel(
            name='pubFacebook',
            fields=[
                ('idPubFacebook', models.AutoField(primary_key=True, serialize=False)),
                ('lienPubFb', models.CharField(max_length=255, verbose_name='lien')),
                ('DateFb', models.DateTimeField(verbose_name='date de publication')),
                ('validerFb', models.BooleanField(blank=True, default=False, null=True, verbose_name='validée')),
                ('refuserFb', models.BooleanField(blank=True, default=False, null=True, verbose_name='refusée')),
                ('idModerateurFb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fb_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
            ],
        ),
    ]
