# Generated by Django 3.0.4 on 2020-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubfacebook',
            name='DateFb',
            field=models.DateTimeField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='pubfacebook',
            name='lienPubFb',
            field=models.CharField(max_length=255, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='pubfacebook',
            name='validerFb',
            field=models.BooleanField(default=False, verbose_name='validée'),
        ),
        migrations.AlterField(
            model_name='pubsiteweb',
            name='DateSw',
            field=models.DateTimeField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='pubsiteweb',
            name='lienPubWeb',
            field=models.CharField(max_length=255, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='pubsiteweb',
            name='validerSw',
            field=models.BooleanField(default=False, verbose_name='validée'),
        ),
        migrations.AlterField(
            model_name='pubyoutube',
            name='DateYt',
            field=models.DateTimeField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='pubyoutube',
            name='lienPubYt',
            field=models.CharField(max_length=255, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='pubyoutube',
            name='validerYt',
            field=models.BooleanField(default=False, verbose_name='validée'),
        ),
    ]
