# Generated by Django 2.2.13 on 2020-06-20 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubyoutube',
            old_name='DateYt',
            new_name='dateYt',
        ),
        migrations.RemoveField(
            model_name='pubyoutube',
            name='lienPubYt',
        ),
        migrations.AddField(
            model_name='article',
            name='idModerateurSw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur'),
        ),
        migrations.AddField(
            model_name='article',
            name='refuserAr',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='refusée'),
        ),
        migrations.AddField(
            model_name='article',
            name='validerAr',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='validée'),
        ),
        migrations.AddField(
            model_name='pubyoutube',
            name='chaineYt',
            field=models.CharField(default='', max_length=255, verbose_name='chaine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubyoutube',
            name='titreYt',
            field=models.CharField(default='', max_length=512, verbose_name='titre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubyoutube',
            name='videoId',
            field=models.CharField(default='', max_length=255, verbose_name='video_id'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='pubSiteWeb',
        ),
    ]
