# Generated by Django 3.0.4 on 2020-05-26 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubfacebook',
            name='DateFb',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 17, 8, 26, 840636, tzinfo=utc), verbose_name='date de publication'),
        ),
    ]
