# Generated by Django 3.0.4 on 2020-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0002_auto_20200526_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubfacebook',
            name='DateFb',
            field=models.DateTimeField(auto_now=True, verbose_name='date de publication'),
        ),
    ]
