# Generated by Django 3.0.3 on 2020-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0003_auto_20200522_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brasserie',
            field=models.CharField(max_length=200),
        ),
    ]
