# Generated by Django 3.0.4 on 2020-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0003_auto_20200526_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsiteweb',
            name='DateSw',
            field=models.DateTimeField(auto_now=True, verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='pubyoutube',
            name='DateYt',
            field=models.DateTimeField(auto_now=True, verbose_name='date de publication'),
        ),
    ]
