# Generated by Django 2.2.13 on 2020-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0004_auto_20200620_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='refuserAr',
        ),
        migrations.RemoveField(
            model_name='pubgooglenews',
            name='refuserGN',
        ),
        migrations.RemoveField(
            model_name='pubyoutube',
            name='refuserYt',
        ),
        migrations.AlterField(
            model_name='article',
            name='validerAr',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='validée'),
        ),
        migrations.AlterField(
            model_name='pubgooglenews',
            name='validerGN',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='validée'),
        ),
        migrations.AlterField(
            model_name='pubyoutube',
            name='validerYt',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='validée'),
        ),
    ]
