# Generated by Django 3.0.3 on 2020-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0004_auto_20200522_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='degre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
