# Generated by Django 3.0.3 on 2020-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0005_auto_20200522_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=512, verbose_name='titre')),
                ('lien', models.CharField(max_length=512, verbose_name='lien')),
                ('source', models.CharField(max_length=512, verbose_name='source')),
                ('date', models.DateTimeField(verbose_name='date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='WHOArticleAr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=512, verbose_name='titre')),
                ('lien', models.CharField(max_length=512, verbose_name='lien')),
            ],
        ),
    ]
