# Generated by Django 2.2.13 on 2020-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robots', '0005_auto_20200620_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubgooglenews',
            name='auteur',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='pubgooglenews',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='source'),
        ),
    ]
