# Generated by Django 3.0.4 on 2020-03-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nomRegion', models.CharField(max_length=30, verbose_name='nom de la région')),
                ('is_risque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='statistiqueRegion',
            fields=[
                ('idStatistique', models.AutoField(primary_key=True, serialize=False)),
                ('nbrPorteurVirus', models.IntegerField(default=0, verbose_name='Nombre de proteurs')),
                ('casConfirme', models.IntegerField(default=0, verbose_name='cas confirmés')),
                ('casRetablis', models.IntegerField(default=0, verbose_name='cas retablis')),
                ('nbrDeces', models.IntegerField(default=0, verbose_name='Nombre de deces')),
                ('nbrGuerisons', models.IntegerField(default=0, verbose_name='Nombre de guerisons')),
                ('dateSt', models.DateTimeField(auto_now=True, verbose_name='date de Statistique')),
                ('validerSt', models.IntegerField(blank=True, default=0, null=True, verbose_name='validée')),
                ('refuserSt', models.IntegerField(blank=True, default=0, null=True, verbose_name='refusé')),
                ('idModerateurSt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='St_moderateur', to=settings.AUTH_USER_MODEL, verbose_name='moderateur')),
                ('idRegionSt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region', verbose_name='region')),
            ],
        ),
    ]
