# Generated by Django 3.0.4 on 2020-03-25 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regionRisque',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nomRegion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='statistiqueRegion',
            fields=[
                ('idStatistique', models.AutoField(primary_key=True, serialize=False)),
                ('nbrPorteurVirus', models.IntegerField(default=0)),
                ('casConfirme', models.IntegerField(default=0)),
                ('casRetablis', models.IntegerField(default=0)),
                ('nbrDeces', models.IntegerField(default=0)),
                ('nbrGuerisons', models.IntegerField(default=0)),
                ('validerSt', models.IntegerField(default=0)),
                ('idRegionSt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Region.regionRisque', verbose_name='region')),
            ],
        ),
    ]
