# Generated by Django 3.0.4 on 2020-03-25 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiqueregion',
            name='idRegionSt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.regionRisque', verbose_name='region'),
        ),
    ]
