# Generated by Django 3.0.3 on 2020-03-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiqueregion',
            name='dateSt',
            field=models.DateTimeField(auto_now=True, verbose_name='date de Statistique'),
        ),
    ]
