# Generated by Django 3.0.3 on 2020-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0002_auto_20200510_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiqueregion',
            name='dateSt',
            field=models.DateTimeField(verbose_name='date de Statistique'),
        ),
    ]
