# Generated by Django 3.0.4 on 2020-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0002_auto_20200325_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionrisque',
            name='nomRegion',
            field=models.CharField(max_length=30, verbose_name='nom de la région'),
        ),
        migrations.AlterField(
            model_name='statistiqueregion',
            name='casConfirme',
            field=models.IntegerField(default=0, verbose_name='cas confirmés'),
        ),
        migrations.AlterField(
            model_name='statistiqueregion',
            name='casRetablis',
            field=models.IntegerField(default=0, verbose_name='cas retablis'),
        ),
        migrations.AlterField(
            model_name='statistiqueregion',
            name='nbrDeces',
            field=models.IntegerField(default=0, verbose_name='Nombre de deces'),
        ),
        migrations.AlterField(
            model_name='statistiqueregion',
            name='nbrGuerisons',
            field=models.IntegerField(default=0, verbose_name='Nombre de guerisons'),
        ),
        migrations.AlterField(
            model_name='statistiqueregion',
            name='nbrPorteurVirus',
            field=models.IntegerField(default=0, verbose_name='Nombre de proteurs'),
        ),
        migrations.AlterField(
            model_name='statistiqueregion',
            name='validerSt',
            field=models.IntegerField(default=0, verbose_name='validée'),
        ),
    ]
