# Generated by Django 3.0.3 on 2020-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0003_auto_20200325_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionrisque',
            name='is_resque',
            field=models.BooleanField(default=False),
        ),
    ]
