# Generated by Django 3.0.3 on 2020-03-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0004_regionrisque_is_resque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regionRisque',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='is_resque',
            new_name='is_risque',
        ),
    ]
