# Generated by Django 3.0.4 on 2020-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_auto_20200325_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifutilisateur',
            name='contenuNotif',
            field=models.TextField(verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='notifutilisateur',
            name='typeNotif',
            field=models.CharField(choices=[('zd', 'zone dangereuse'), ('vv', 'video validée'), ('md', 'malade'), ('sg', 'signalement')], max_length=2, verbose_name='type'),
        ),
    ]
